app/modules/admin/controllers/RoleController.php
<?php

namespace app\modules\admin\controllers;

use Yii;
use app\models\Role;
use app\models\RoleSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * RoleController implements the CRUD actions for Role model.
 */
class RoleController extends CustomController
{
    /**
     * @inheritdoc
     */
   /* public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }*/

    /**
     * Lists all Role models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new RoleSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Role model.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Role model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Role();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->name]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Role model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->name]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Role model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Role model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Role the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Role::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

app/modules/admin/controllers/UserController.php
<?php

namespace app\modules\admin\controllers;

use app\models\AuthAssignment;
use app\models\Role;
use Yii;
use app\models\User;
use yii\data\ActiveDataProvider;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends CustomController
{
    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $adminID = ArrayHelper::getColumn(AuthAssignment::find()->select(['user_id'])->where(['item_name' => 'Admin'])->all(), 'user_id');
        //AuthAssignment::find()->where(['item_name' => 'USer'])->all();
        $user = User::find()->where(['id' => $adminID])->all();

        $admindataProviderRole = new ActiveDataProvider([
            'query' => User::find()->where(['id' => $adminID]),
        ]);

        $userID = ArrayHelper::getColumn(AuthAssignment::find()->select(['user_id'])->where(['item_name' => 'USer'])->all(), 'user_id');
        //AuthAssignment::find()->where(['item_name' => 'USer'])->all();
        $user = User::find()->where(['id' => $userID])->all();

        $dataProviderRole = new ActiveDataProvider([
            'query' => User::find()->where(['id' => $userID]),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProviderRole,
            'admindataProvider' => $admindataProviderRole,

        ]);
    }

    /**
     * Displays a single User model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new User();

        if ($model->load(Yii::$app->request->post())) {
            $model->active = 1;
            $model->create_at = time();
            if($model->save())
            {
                echo $model->password;
                exit();
                $model->save_assignment($model->id , $model->auth_item);
                Yii::$app->session->setFlash('alert', ['success', 'عملیات مورد نظر با موفقیت انجام  شد.']);
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }
    public function actionUserCreate(){
        $model = new User();
        if ($model->load(Yii::$app->request->post())) {
            $model->active = 1;
            $model->create_at = time();
            if($model->save())
            {
                $model->save_assignment($model->id , $model->auth_item);
                echo $model->password;
                exit();
                Yii::$app->session->setFlash('alert', ['success', 'عملیات مورد نظر با موفقیت انجام  شد.']);
                return $this->redirect(['view', 'id' => $model->id]);
            }else{
                print_r($model->getErrors());
            }
        } else {
            return $this->render('user-create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $model->save_assignment($id , $model->auth_item);
            Yii::$app->session->setFlash('alert', ['success', 'عملیات مورد نظر با موفقیت انجام  شد.']);
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $assign = AuthAssignment::findOne(['user_id' => $id]);
        if($assign!= null){
            $assign->delete();
        }

        $this->findModel($id)->delete();

        Yii::$app->session->setFlash('alert', ['success', 'عملیات مورد نظر با موفقیت انجام  شد.']);
        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

app/modules/admin/views/user/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\User */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="box box-info">
    <div class="box-header with-border">
        <h3 class="box-title"><?= Html::encode($this->title) ?></h3>
    </div>

    <div class="box-body">

        <div class="user-form">

            <?php $form = ActiveForm::begin(); ?>


            <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

            <?= $form->field($model, 'user_name')->textInput(['maxlength' => true]) ?>

            <?= $form->field($model, 'password')->passwordInput(['maxlength' => true]) ?>

            <?= $form->field($model, 'full_name')->textInput(['maxlength' => true]) ?>
            <div class="form-group field-user-full_name has-success">
                <label class="control-label" for="user-full_name"></label>
                <?php
                echo Html::activeDropDownList($model,'auth_item',\yii\helpers\ArrayHelper::map(\app\models\role::findAll(['type' => 1]),'name','name'),['class' => 'form-control']);
                ?>

                <div class="help-block"></div>
            </div>


            <?php if(!$model->isNewRecord) :?>

                <?= $form->field($model, 'active')->checkbox() ?>

            <?php endif;?>

            <div class="form-group">
                <?= Html::submitButton($model->isNewRecord ? 'افزودن' : 'ویرایش', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
            </div>

            <?php ActiveForm::end(); ?>

        </div>

    </div>
</div>

app/modules/admin/views/user/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = 'افزودن ادمین';
$this->params['breadcrumbs'][] = ['label' => 'ادمین', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

app/modules/admin/views/user/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'ادمین';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="box box-info">
    <div class="box-header with-border">
        <h3 class="box-title"><?= Html::encode($this->title) ?></h3>
    </div>

  <!--  <ul class="nav nav-tabs">
        <li class="active"><a data-toggle="tab" href="#home">Home</a></li>
        <li><a data-toggle="tab" href="#menu1">role</a></li>

    </ul>-->

    <div class="tab-content">
        <div id="home" class="tab-pane fade in active">
            <div class="box-body">

                <div class="user-index">

                    <ul class="nav nav-tabs">
                    <li class="active"><a data-toggle="tab" href="#home">مدیران</a></li>
                    <li><a data-toggle="tab" href="#menu1">کاربران</a></li>
                    </ul>
                    <?php Pjax::begin(); ?>
                    <div class="tab-content">
                        <div id="home" class="tab-pane fade in active">
                            <p>
                                <?= Html::a('افزودن ادمین', ['create'], ['class' => 'btn btn-success']) ?>
                            </p>
                            <?= GridView::widget([
                                'dataProvider' => $admindataProvider,
                                'columns' => [
                                    //['class' => 'yii\grid\SerialColumn'],

                                    'id',
                                    'full_name',
                                    'user_name',
                                    //'password',
                                    //'auth_key',
                                    // 'password_reset_token',
                                    // 'email:email',
                                    'active',
                                    [

                                        'attribute' => 'auth_item',
                                        'content' => function($data){
                                            $d=\app\models\AuthAssignment::findOne(['user_id' => $data->id]);
                                            if($d!=null){
                                                return $d->item_name;
                                            }else{

                                            }

                                        }
                                    ],
                                    // 'create_at',

                                    [
                                        'attribute' => 'create_at',
                                        'format' => 'raw',
                                        'content' => function($data){
                                            return \app\components\General::persianDate($data->create_at);
                                        }
                                    ],

                                    ['class' => 'yii\grid\ActionColumn'],
                                ],
                            ]); ?>
                        </div>
                        <div id="menu1" class="tab-pane fade">
                            <p>
                                <?= Html::a('افزودن کاربر', ['user-create'], ['class' => 'btn btn-success']) ?>
                            </p>
                            <?= GridView::widget([
                                'dataProvider' => $dataProvider,
                                'columns' => [
                                    //['class' => 'yii\grid\SerialColumn'],

                                    'id',
                                    'full_name',
                                    'user_name',
                                    //'password',
                                    //'auth_key',
                                    // 'password_reset_token',
                                    // 'email:email',
                                    'active',
                                    [

                                        'attribute' => 'auth_item',
                                        'content' => function($data){
                                            $d=\app\models\AuthAssignment::findOne(['user_id' => $data->id]);
                                            if($d!=null){
                                                return $d->item_name;
                                            }else{

                                            }

                                        }
                                    ],
                                    // 'create_at',

                                    [
                                        'attribute' => 'create_at',
                                        'format' => 'raw',
                                        'content' => function($data){
                                            return \app\components\General::persianDate($data->create_at);
                                        }
                                    ],

                                    ['class' => 'yii\grid\ActionColumn'],
                                ],
                            ]); ?>
                        </div>

                    </div>



                    <?php Pjax::end(); ?>
                </div>
            </div>
        </div>
    <!--    <div id="menu1" class="tab-pane fade">
            <div class="box-body">

                <div class="user-index">
                    <p>
                        <?/*= Html::a('افزودن نقش', ['role/create'], ['class' => 'btn btn-success']) */?>
                    </p>
                    <?php /*Pjax::begin(); */?>    <?/*= GridView::widget([
                        'dataProvider' => $dataProviderRole,
                        'columns' => [
                            //['class' => 'yii\grid\SerialColumn'],

                           // 'id',
                            'name',
                           // 'type',
                            //'password',
                            //'auth_key',
                            // 'password_reset_token',
                            // 'email:email',
                            'description',


                          //  'created_at',

                            [
                                'class' => 'yii\grid\ActionColumn',
                                'controller' => 'role',

                            ],
                        ],
                    ]); */?>
                    <?php /*Pjax::end(); */?>
                    role
                </div>
            </div>
        </div>-->

    </div>


    </div>

app/modules/admin/views/user/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = 'ویرایش ادمین: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'ادمین', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'ویرایش';
?>
<div class="user-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

app/modules/admin/views/user/user-create.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\User */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="box box-info">
    <div class="box-header with-border">
        <h3 class="box-title"><?= Html::encode($this->title) ?></h3>
    </div>

    <div class="box-body">

        <div class="user-form">

            <?php $form = ActiveForm::begin(); ?>


            <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

            <?= $form->field($model, 'user_name')->textInput(['maxlength' => true]) ?>

            <?= $form->field($model, 'password')->passwordInput(['maxlength' => true]) ?>

            <?= $form->field($model, 'full_name')->textInput(['maxlength' => true]) ?>
            <div class="form-group field-user-full_name has-success">
                <label class="control-label" for="user-full_name"></label>
                <?php
                echo Html::activeDropDownList($model,'auth_item',\yii\helpers\ArrayHelper::map(\app\models\role::findAll(['type' => 2]),'name','name'),['class' => 'form-control']);
                ?>

                <div class="help-block"></div>
            </div>


            <?php if(!$model->isNewRecord) :?>

                <?= $form->field($model, 'active')->checkbox() ?>

            <?php endif;?>

            <div class="form-group">
                <?= Html::submitButton($model->isNewRecord ? 'افزودن' : 'ویرایش', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
            </div>

            <?php ActiveForm::end(); ?>

        </div>

    </div>
</div>

app/modules/admin/views/user/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'ادمین', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="box box-info">
    <div class="box-header with-border">
        <h3 class="box-title"><?= Html::encode($this->title) ?></h3>
    </div>

    <div class="box-body">
        <div class="user-view">

            <p>
                <?= Html::a('ویرایش', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
                <?= Html::a('حذف', ['delete', 'id' => $model->id], [
                    'class' => 'btn btn-danger',
                    'data' => [
                        'confirm' => 'Are you sure you want to delete this item?',
                        'method' => 'post',
                    ],
                ]) ?>
            </p>

            <?= DetailView::widget([
                'model' => $model,
                'attributes' => [
                    'id',
                    'full_name',
                    'user_name',
                    //'password',
                    //'auth_key',
                    //'password_reset_token',
                    'email:email',
                    // 'active',
                    [
                        'attribute' => 'active',
                        'format' => 'raw',
                        'value' => $model->statusArr[$model->active]
                    ],
                    //'create_at',
                    [
                        'attribute' => 'create_at',
                        'format' => 'raw',
                        'value' => \app\components\General::persianDate($model->create_at),
                    ]
                ],
            ]) ?>

        </div>
    </div>
</div>